spring:
  profiles:
    active: local #로컬 + ec2 내부 dev 환경
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
