name: CI/CD Pipeline

on:
  push:
    branches: [ dev ]  # dev 브랜치에 push될 때 실행
  pull_request:
    branches: [ dev ]  # dev 브랜치로 PR 생성 시 실행

jobs:
  build:
    runs-on: pickify  # self-hosted runner

    steps:
      - uses: actions/checkout@v4  # 저장소 코드 체크아웃
        with:
          fetch-depth: 0  # 전체 Git 기록을 가져옴

      - name: Set up JDK 21  # Java 개발 킷 설정
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Gradle 캐싱 - 빌드 시간 향상
      - name: Gradle Caching
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make application.yml  # application.yml 파일 생성
        run: |
          cd ./src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" > ./application.yml
        shell: bash

      - name: Grant execute permission for gradlew  # gradlew 실행 권한 부여
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run build
        run: ./gradlew build

        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_HOST_NAME: ${{ secrets.DB_HOST_NAME }}
          DB_HOST_PASSWORD: ${{ secrets.DB_HOST_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRATION_TIME: ${{ secrets.JWT_EXPIRATION_TIME }}

      - name: Move jar file to home directory
        run: |
          find build/libs -name '*.jar' ! -name '*plain.jar' -exec mv {} /home/${{ secrets.EC2_HOST }}/pickify-spring.jar \;
            

  deploy:
    needs: build  # build 작업이 성공적으로 완료된 후 실행
    runs-on: pickify  # self-hosted runner에서 실행

    steps:
      - name: Stop Existing Application  # 기존 Java 프로세스 종료
        run: |
          pgrep java | xargs -r kill -15
          sleep 4

      - name: Start Application  # 새로운 JAR 실행
        run: |
          nohup java -jar /home/ubuntu/pickify-spring.jar > /home/ubuntu/logs/app.log 2>&1 & disown
